import Navbar from "@/components/ui/navbar";
import "@/styles/globals.css";

import { Raleway } from "next/font/google";
import Footer from "./_components/footer";

const raleway = Raleway({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html data-theme="light" lang="en">
      <body
        className={`font-sans ${raleway.variable} flex w-full flex-col gap-10`}
      >
        <Navbar />

        {children}

        <Footer />
      </body>
    </html>
  );
}
